# Generated by Django 4.1.3 on 2022-11-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_author_birth_date_alter_author_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='author',
            name='death_date',
            field=models.DateField(blank=True, null=True, verbose_name='Death date'),
        ),
        migrations.AlterField(
            model_name='author',
            name='descreption',
            field=models.TextField(blank=True, null=True, verbose_name='Descreption'),
        ),
        migrations.AlterField(
            model_name='book',
            name='added_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='descreption',
            field=models.TextField(blank=True, null=True, verbose_name='Descreption'),
        ),
    ]
