# Generated by Django 4.1.3 on 2022-11-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_author_birth_date_alter_author_death_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads/% Y/% m/% d/'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
