# Generated by Django 4.1.3 on 2022-11-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_author_photo_alter_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads/authors/photo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads/books/cover/%Y/%m/%d/'),
        ),
    ]
